import { StyleSheet } from 'react-native';

export const COLORS = {
  primary: '#1A237E',
  primaryLight: '#283593',
  accent: '#FF6F00',
  accentLight: '#FFB300',
  success: '#2E7D32',
  warning: '#E65100',
  danger: '#C62828',
  info: '#0277BD',
  bg: '#F5F6FA',
  card: '#FFFFFF',
  border: '#E8EAF6',
  text: '#1A1A2E',
  textLight: '#5C6BC0',
  textMuted: '#9E9E9E',
  white: '#FFFFFF',

  // Status colors
  submitted: '#7B1FA2',
  quote_requested: '#0891B2',
  assigned: '#0277BD',
  quoted: '#E65100',
  quote_sent_to_resident: '#00838F',
  quote_accepted: '#2E7D32',
  quote_rejected: '#C62828',
  approved_to_start: '#7C3AED',
  work_in_progress: '#1565C0',
  work_completed: '#2E7D32',
  payment_requested_to_admin: '#E65100',
  payment_requested_to_resident: '#FF6F00',
  payment_received: '#0277BD',
  paid_to_vendor: '#1B5E20',
};

export const STATUS_LABELS = {
  submitted: 'Submitted',
  quote_requested: 'Quote Requested',
  assigned: 'Vendor Assigned',
  quoted: 'Quote Received',
  quote_sent_to_resident: 'Quote Sent to Resident',
  quote_accepted: 'Quote Accepted',
  quote_rejected: 'Quote Rejected',
  approved_to_start: 'Vendor Approved',
  work_in_progress: 'Work In Progress',
  work_completed: 'Work Completed',
  payment_requested_to_admin: 'Awaiting Payment',
  payment_requested_to_resident: 'Payment Requested',
  payment_received: 'Payment Received',
  paid_to_vendor: 'Completed & Paid',
};

export const globalStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: COLORS.bg },
  card: {
    backgroundColor: COLORS.card,
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  cardTitle: { fontSize: 16, fontWeight: '700', color: COLORS.text, marginBottom: 4 },
  cardSub: { fontSize: 13, color: COLORS.textMuted },
  badge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
    alignSelf: 'flex-start',
  },
  badgeText: { fontSize: 11, fontWeight: '700', color: '#fff' },
  btn: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnPrimary: { backgroundColor: COLORS.primary },
  btnAccent: { backgroundColor: COLORS.accent },
  btnSuccess: { backgroundColor: COLORS.success },
  btnDanger: { backgroundColor: COLORS.danger },
  btnText: { color: '#fff', fontWeight: '700', fontSize: 14 },
  input: {
    backgroundColor: '#F8F9FF',
    borderWidth: 1.5,
    borderColor: COLORS.border,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    color: COLORS.text,
    marginBottom: 12,
  },
  label: { fontSize: 13, fontWeight: '600', color: COLORS.textLight, marginBottom: 6 },
  sectionHeader: { fontSize: 20, fontWeight: '800', color: COLORS.text, marginBottom: 16 },
  emptyState: { alignItems: 'center', paddingVertical: 48, opacity: 0.5 },
  emptyText: { fontSize: 15, color: COLORS.textMuted, marginTop: 8 },
});

